name: Web Tools Node 18 OpenJDK 8 Bullseye Version

on:
  push:
    branches:
      - master
    paths:
      # '*' matches any character except '/'
      - 'node18-openjdk8-bullseye/*'
      - '.github/workflows/docker-build-node18-openjdk8-bullseye.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Docker login
      env:
        DOCKER_HUB_USERNAME: ${{ secrets. DOCKER_HUB_USERNAME }} 
        DOCKER_HUB_PASSWORD: ${{ secrets. DOCKER_HUB_PASSWORD }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      run: |
        echo $DOCKER_HUB_PASSWORD | docker login --username $DOCKER_HUB_USERNAME --password-stdin
        echo $GITHUB_TOKEN | docker login docker.pkg.github.com --username $GITHUB_ACTOR --password-stdin

    - name: Build & Push web-tools
      run: |
       cd node18-openjdk8-bullseye
       IMAGE_NAME=ringcentral/web-tools
       GH_DOCKER_PKG_IMAGE_NAME=docker.pkg.github.com/ringcentral-docker/web-tools/web-tools

       OPENJDK_VERSION="$(awk -F '[=]' '/ENV OPENJDK_VERSION/ {print $2}' Dockerfile)"
       NODE_VERSION="$(awk -F '[:-]' '/FROM/ {print $2}' Dockerfile)"
       NODE_MAJOR_VERSION="$(awk -F '[:-]' '/FROM/ {print $2}' Dockerfile | cut -d "." -f 1)"

       docker build --tag ${IMAGE_NAME} --file Dockerfile .

       docker tag "${IMAGE_NAME}" "${IMAGE_NAME}:node${NODE_MAJOR_VERSION}-openjdk${OPENJDK_VERSION}-bullseye"
       docker push "${IMAGE_NAME}:node${NODE_MAJOR_VERSION}-openjdk${OPENJDK_VERSION}-bullseye"

       docker tag "${IMAGE_NAME}" "${GH_DOCKER_PKG_IMAGE_NAME}:node${NODE_MAJOR_VERSION}-openjdk${OPENJDK_VERSION}-bullseye"
       docker push "${GH_DOCKER_PKG_IMAGE_NAME}:node${NODE_MAJOR_VERSION}-openjdk${OPENJDK_VERSION}-bullseye"